GET /me
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiTUVNQkVSIiwidHlwZSI6IkNPTVBBTklFIiwic3ViIjoiNGJiMGJjMjItNTU1Ni00ZWM2LTk3YTYtODExZDc0YzQ2MmNiIiwiaWF0IjoxNjk0NzE2MjM2LCJleHAiOjE2OTczMDgyMzZ9.ZPZLn9d_N8Iz5HgPB4BIw-KQe0bUCWS2N5NHmdumGh0
