GET /backoffice/accounts?search=mauro
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJ0eXBlIjpudWxsLCJzdWIiOiJmOTc2MmQ0Mi1kY2FhLTQ3NTQtOWQ3MS00MzgzYTdlYzIzNjQiLCJpYXQiOjE2OTIxMTcwNzYsImV4cCI6MTY5NDcwOTA3Nn0.6wa58zhtDkzzJrtM_5ml0YHTcMCYrnnZ8l0xq1U8p60