GET /backoffice/transactions?page=2&endDate=2023-04-01T02:59:59.999Z&startDate=2023-08-01T03:00:00.000Z&per_page=10
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJ0eXBlIjpudWxsLCJzdWIiOiJmOTc2MmQ0Mi1kY2FhLTQ3NTQtOWQ3MS00MzgzYTdlYzIzNjQiLCJpYXQiOjE2OTIxMTcwNzYsImV4cCI6MTY5NDcwOTA3Nn0.6wa58zhtDkzzJrtM_5ml0YHTcMCYrnnZ8l0xq1U8p60
###
GET /backoffice/transactions/9de8b11e-2ea7-4037-994c-a6c6312af4f0
Host: localhost:3333
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQURNSU4iLCJ0eXBlIjpudWxsLCJzdWIiOiJmOTc2MmQ0Mi1kY2FhLTQ3NTQtOWQ3MS00MzgzYTdlYzIzNjQiLCJpYXQiOjE2OTIxMTcwNzYsImV4cCI6MTY5NDcwOTA3Nn0.6wa58zhtDkzzJrtM_5ml0YHTcMCYrnnZ8l0xq1U8p60